
title: Segmentation using VollSeg
author: Varun Kapoor
logo: images/kapoorlogo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: vollseg-napari.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/Kapoorlabs-CAPED/vollseg-napari/ 
  path_to_book: docs 
  branch: master  


html:
  use_issues_button: true
  use_repository_button: true
  